nav:
    # - Home: index.md
    # - Practical sessions:
    #     # - Connecting to WIS2 xxxx over MQTT: practical-sessions/connecting-to-wis2-over-mqtt.md
    #     # - Accessing your student VM: practical-sessions/accessing-your-student-vm.md
    #     # - Initializing wis2box: practical-sessions/initializing-wis2box.md
    #     # - Configuring datasets in wis2box: practical-sessions/configuring-wis2box-datasets.md
    #     - Configuring station metadata: practical-sessions/configuring-station-metadata.md
    #     - Monitoring WIS2 notifications: practical-sessions/monitoring-wis2-notifications.md
    #     - Converting SYNOP data to BUFR from the command line: practical-sessions/converting-synop-data-to-bufr.md
    #     - Converting SYNOP data to BUFR using the wis2box-webapp: practical-sessions/converting-synop-data-to-bufr-form.md
    #     - Converting CSV data to BUFR: practical-sessions/converting-csv-data-to-bufr.md
    #     - Automating data ingestion: practical-sessions/automating-data-ingestion.md
    #     - Adding GTS-headers to WIS2 notifications: practical-sessions/adding-gts-headers-to-wis2-notifications.md
    #     - Setting up a recommended dataset with access control: practical-sessions/datasets-with-access-control.md
    #     - Downloading data from WIS2: practical-sessions/downloading-data-from-wis2.md
    #     - Discovering datasets from the WIS2 Global Discovery Catalogue: practical-sessions/discovering-datasets-from-wis2-gdc.md
    #     - Querying data using the wis2box API: practical-sessions/querying-data-using-the-wis2box-api.md
    #     #- Working with BUFR data: practical-sessions/bufr-command-line-tools.md
    # - Cheatsheets:
    #     - Linux: cheatsheets/linux.md
    #     - Docker: cheatsheets/docker.md
    #     - WIS2 in a box: cheatsheets/wis2box.md
    # - csv2bufr templates:
    #     - AWS hourly: csv2bufr-templates/aws-template.md
    #     - DAYCLI: csv2bufr-templates/daycli-template.md
